# Generated by Django 5.2.8 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('kullaniciID', models.AutoField(primary_key=True, serialize=False)),
                ('rolID', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('yas', models.IntegerField(null=True)),
                ('yasilimit', models.IntegerField(null=True)),
                ('alanID', models.IntegerField(null=True)),
                ('kullaniciDurum', models.CharField(max_length=50, null=True)),
                ('yakinibildirim', models.CharField(max_length=50, null=True)),
                ('Ad', models.CharField(max_length=255)),
                ('Soyad', models.CharField(max_length=255)),
                ('Sifre', models.CharField(max_length=255)),
                ('TC', models.CharField(max_length=20)),
                ('cinsiyet', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"Kullanici"',
                'managed': False,
            },
        ),
    ]
